### GET DASHBOARD METRICS (Calculate + Store)
GET http://localhost:4000/dashboard/calculate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzYzODg3NDc4LCJleHAiOjE3NjM4ODgzNzh9.GXjne7PQgA-PSbAZWX_-XfQ0BplpJRP8CNkM_7mh87s