POST http://localhost:4000/onboarding/form
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY0Mzg0NDk4LCJleHAiOjE3NjQzODUzOTh9.3ozlxMUGURdh9Gkvm0GVywOcJRkqEGxRssqycjh1hHE
Content-Type: application/json

{
  "profile": {
    "age": 28,
    "gender": "Male",
    "heightCm": 178,
    "weightKg": 85,
    "country": "India",
    "state": "Maharastra",
    "phone": "9876543210"
  },
  "fitnessGoals": {
    "primaryGoal": "Fat loss",
    "fitnessLevel": 40,
    "activityLevel": "Moderately Active",
    "dietType": "Vegetarian"
  },
  "healthProfile": {
    "allergies": "Peanuts",
    "injuries": "lower back pain",
    "diseases": "PCOS"
  }
}



###
GET http://localhost:4000/onboarding/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzYzODg1NjE3LCJleHAiOjE3NjM4ODY1MTd9.i7AVmQioOPNHF_ctJtXqXHmWytyi9C9pE7rqWDGU3xQ


###
